spring.application.name=pruebaTecnicaBackendProteccion
server.port=8080
server.servlet.context-path=/api/
app.client.url=*

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#### Database config
spring.datasource.url=jdbc:postgresql://database-1.c3kuw464gzq7.sa-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Z7Ph2ux29atjQQsEcG4b

#### Loggin settings #######
app.logs.level=info
app.logs.console=true


spring.security.user.name=pruebaUser
spring.security.user.password=@drianaVv123
